#!/bin/sh

set -e

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

repo="https://dibblego@bitbucket.org/dibblego/archlinux-install/"
git="https://github.com/tonymorris/archlinux-install-bootstrap/raw/master/git"

pacman --noconfirm --needed -Syq git

function bootstrap() {    
  archlinuxinstall=$(mktemp -d /tmp/archlinux-install.XXXXXX)
  git clone $repo $archlinuxinstall
  cd $archlinuxinstall
  echo $archlinuxinstall
  chmod +x "$archlinuxinstall/archlinux-install"
  "$archlinuxinstall/archlinux-install"
}
bootstrap

